### PR TITLE
"Class"-ify weatherflow2mqtt

### PR DESCRIPTION
**Pull request by natekspencer**
This is my initial attempt to help convert the main running program to an easier to manage class structure to ease future support.

- Removes the option `ADD_FORECAST` and relies on data populated in both `STATION_ID` and `STATION_TOKEN` instead, since `ADD_FORECAST`, by itself, doesn't do anything.
- Automatically determines `ELEVATION` and `UNIT_SYSTEM` in HA Supervisor installs
  - Removes `UNIT_SYSTEM` from config in supervisor

### CODE REVIEW

**Comment by natekspencer** [comment]
Also, I'd be interested in helping to maintain https://github.com/briis/pysmartweatherudp and https://github.com/briis/smartweatherudp

**Comment by briis** [comment]
Perfect Nathan. I am actually in the process of doing that with three other Integrations I have, so if you can do this one, I would be happy.

Yes as you can see the UDP versions of the integration have not been touched for a while, my biggest issue was the `pysmartweatherudp` module. Even though it works, it really needs to be rewritten from scratch. I will put you on both these projects so you can merge PR's yourself.

**Comment by briis** [comment]
You are now invited to both the above repositories.
Is this ready to merge?

**Comment by briis** [comment]
And I added you to this repository also

**Comment by natekspencer** [comment]
> Yes as you can see the UDP versions of the integration have not been touched for a while, my biggest issue was the `pysmartweatherudp` module. Even though it works, it really needs to be rewritten from scratch. I will put you on both these projects so you can merge PR's yourself.

Awesome, my hope with `pysmartweatherudp` is to get it so that this project can also utilize the same module for reading the UDP data, and then adding the additional smarts on top of it.

> Is this ready to merge?

I've been running it on my box and haven't run into any issues. But it might be helpful to just peruse it first and make sure it looks kosher!

**Comment by briis** [comment]
OK, I will merge now, and then test it tomorrow before I do the builds.

Would be great if there could be a shared UDP module - why didn't I think of that :)

I have just rewritten the `smartweather` integration using the `pysmartweatherio`. I decided I wanted to do so many changes, that I started from scratch and renamed it to the domain `weatherflow`. You can look at what I did there in these two repositories: [pyweatherflowrest](https://github.com/briis/pyweatherflowrest) and [weatherflow](https://github.com/briis/hass-weatherflow)

**Comment by briis** [comment]
We might actually be able to use `pyweatherflowrest` to pull the Weather data in to this, so this code can then be removed.

**Comment by natekspencer** [comment]
> We might actually be able to use `pyweatherflowrest` to pull the Weather data in to this, so this code can then be removed.

My thoughts as well!

**Comment by natekspencer** [comment]
It looks like you may have previously started work on a separate package for the udp (https://pypi.org/project/pyweatherflowudp), but it doesn't look like that repository exists anymore. Did you cancel that initial endeavor?

**Comment by briis** [comment]
No, I made it private. But it is very early stages, and I gave up on it again. But we can use this repository, to make a new, that will then stay within the same naming. I reset it to Public. https://github.com/briis/pyweatherflowudp and added you to it.
Feel free to delete and overwrite all that is in there

**Comment by natekspencer** [comment]
> No, I made it private. But it is very early stages, and I gave up on it again. But we can use this repository, to make a new, that will then stay within the same naming. I reset it to Public. https://github.com/briis/pyweatherflowudp and added you to it. Feel free to delete and overwrite all that is in there

Sounds good!

**Comment by briis** [comment]
Just another though, as your are making changes anyway:

- We should remove all the historic attributes, as these are now covered by Home Assistant using the `state_class` parameter. So statistic information is accumulated here, and we don't need to do it in the database. That means the only thing we will still need the database for, are the values that are not persistent upon restart - like rain today, lightning today etc.

**Pull request merged**
