### PR TITLE
Bump pyweatherflowudp to 1.1.1

### PR DESCRIPTION
**Pull request by natekspencer**
Resolves issue #109

### CODE REVIEW

**Comment by briis** [comment]
I will merge this, and build new containers.

**Comment by natekspencer** [comment]
I need to add one more thing to this before you build

**Comment by briis** [comment]
Ok, no worries. You merge again when you are ready to go. I will then build tonight or tomorrow morning,

**Comment by natekspencer** [comment]
It'll be up in just a few seconds

**Pull request merged**
