### PR TITLE
Change entity name to include model and serial number

### PR DESCRIPTION
**Pull request by natekspencer**

### CODE REVIEW

**Comment by briis** [comment]
Testing...

**Comment by briis** [comment]
For an existing installation, the entity_id does not change from wf_SENSOR_NAME, but the Name changes. This must be because we don't change the unique_id. This not as severe a breaking change, as automations do not need to be edited.
I will try and delete my current installation, and see what happens when a new user installs.

**Comment by natekspencer** [comment]
> For an existing installation, the entity_id does not change from wf_SENSOR_NAME, but the Name changes

That's what I was hoping would happen and kind of expected as I had been doing a number of other tests and iterations during the whole process. With a new install, it will show up with the new names. But this is good because those who have already renamed the device should see minimal changes.

**Comment by briis** [comment]
It works as expected. You can merge this👍🏻

**Pull request merged**
