### PR TITLE
HASS addon repository support

### PR DESCRIPTION
**Pull request by natekspencer**
This should allow for this repository to easily be added to the Supervisor Add-on Store and then be installed, configured and started all from the Home Assistant supervisor.

A new docker image will be needed due to the changes on `weatherflow2mqtt/weatherflow_mqtt.py` to support reading the options for the HA add-on. Also, the *config.json*'s `version` tag will need to be updated with the new image so that it can pull the correct image down without having to build.

### CODE REVIEW

**Comment by briis** [comment]
Cool Nathan. I have no experience with developing for the Add-On part of Home Assistant, but with these changes, it will then be possible to add this as a Custom Repository in the Add-On Store?

**Comment by natekspencer** [comment]
Correct. It should also make it so that the supervisor doesn't complain about unknown docker containers running on the system, thus allowing/maintaining a supported installation.

**Comment by natekspencer** [comment]
Here's a couple of screenshots of what it would look like:
Screen Shot 2021-11-10 at 1 40 25 AM
Screen Shot 2021-11-10 at 1 40 43 AM

**Comment by briis** [comment]
Fantastic. I will merge and build the new containers. Thanks a lot Nathan.

**Comment by natekspencer** [comment]
> Fantastic. I will merge and build the new containers. Thanks a lot Nathan.

Awesome, thank you for all your work on this! Hopefully this helps make it a little more accessible to others, too. It's my first addon experience as well, so I'll help and improve it as I learn more!

**Comment by briis** [comment]
Last question: I can just build the containers as I always did? Or do they require any special tags or something when building to work with the Add-On store?

**Comment by natekspencer** [comment]
> Last question: I can just build the containers as I always did? Or do they require any special tags or something when building to work with the Add-On store?

You can just build as before. The only thing that is needed after the build, or once you know the version number anyway, is to update the `config.json` file (https://github.com/briis/hass-weatherflow2mqtt/blob/main/config.json#L7) so that the image can be easily downloaded from docker right into the HA supervisor

**Comment by briis** [comment]
Got it. Thanks
It is now build and pushed to docker.io Let me know if everything works (Should be V2.2.0)

**Comment by natekspencer** [comment]
> Got it. Thanks It is now build and pushed to docker.io Let me know if everything works (Should be V2.2.0)

It worked perfectly!

**Comment by briis** [comment]
Same for me !!!! Again, thanks for helping out - this was a long wanted thing, I just never got around to look at.

**Comment by briis** [comment]
The program uses a SQLite database for storing some values, with this setup, have you found where the database is located?

**Comment by natekspencer** [comment]
> The program uses a SQLite database for storing some values, with this setup, have you found where the database is located?

It's stored in the /data folder for the addons. For my supervised installation, it's:

`/usr/share/hassio/addons/data/67f4b1af_weatherflow2mqtt`

(The "67f4b1af" is a hash slug generated by supervisor based on the repository url if I remember correctly)

**Comment by natekspencer** [comment]
> The program uses a SQLite database for storing some values, with this setup, have you found where the database is located?

This also relates to the next changes I'd like to discuss and potentially see/help implement. If you look at the [supervisor documentation](https://developers.home-assistant.io/docs/add-ons/configuration/#add-on-config), supervisor can mount/bind a few volumes based on some configurations in the `config.json` file.

By default, [supervisor](https://github.com/home-assistant/supervisor/blob/main/supervisor/docker/addon.py#L293) always mounts/binds the `/data` folder as `/data:rw` in the container. If you look in the [config.json](https://github.com/briis/hass-weatherflow2mqtt/blob/main/config.json#L21) file, I already added a map for `/config:rw` which supervisor then mounts/binds to a `/config` folder in the container. Right now, this container only uses a `/usr/local/config` volume. It also uses an EXTERNAL_DIRECTORY variable to further allow changes, which I utilized to help get it to write to the `/data` folder.

After mentioning the above, it would be nice to have a bound `/data` and `/config` folder in this container, instead of `/usr/local/config`, but that would require more changes in the docker container. This would then allow us to potentially create a `weatherflow2mqtt` folder in the HA `config` folder for users to more easily paste a customized `config.yaml`.

One point to mention is that the default `/data` folder is the recommended storage location (aka weatherflow2mqtt.db) for supervisor supported addons.

**Comment by briis** [comment]
I would happily accept your help in making the proposed change. So when you have the time, just go do, and I can review it.

**Comment by natekspencer** [comment]
> I would happily accept your help in making the proposed change. So when you have the time, just go do, and I can review it.

Sounds great. Also, thanks for all the documentation updates for the add-on, makes it look legit!

**Comment by briis** [comment]
It is legit ! :)

**Pull request merged**
