### PR TITLE
Update helpers.py

### PR DESCRIPTION
**Pull request by GlennGoddard**
Improve visibility calculation based on dew point conditions.

### CODE REVIEW

**Comment by GlennGoddard** [comment]
See comments in the closed issue for visibility to see the equation I used if not clear in the code.

**Comment by briis** [comment]
Very good Glenn, Thanks. I will push out a new release in a few minutes.

**Comment by GlennGoddard** [comment]
I have not seen the updated image, did you move the docker image again?

**Comment by briis** [comment]
You put in the wrong address in PR. The image is in briis/weatherflow2mqtt. I have corrected the Readme.

**Comment by GlennGoddard** [comment]
Ok, I will test when I get home then.

**Pull request merged**
