### PR TITLE
Fix snow_probability conditions

### PR DESCRIPTION
**Pull request by GlennGoddard**
Replaced '&&' with 'and'

'&&' is 'and' in java-script, I missed converting it to 'and'

### CODE REVIEW

**Comment by GlennGoddard** [comment]
I figured out what was 'wrong' with the fog_probability and it may be my 'mistake' is actually better than what I was testing against.  I will continue to monitor and change if needed.

I did not finish some conversions, but I did update the comments that is what messed me up finding it.  It is more responsive than my version running in Node-Red so I am just going to continue to watch and see if I need to tweak it or not.

**Comment by briis** [comment]
Hi Glenn,
The changes you make in this request are already done in the current code and part of the `dev` branch you are testing against. So I will not merge this PR as it is already done.

**Comment by GlennGoddard** [comment]
So, you did accept this PR.  You just did it before I wrote it.

I'll close it when I turn my computer on in the morning (my morning).

**Comment by briis** [comment]
Exactly - You and I are in total Sync 😁

**Comment by GlennGoddard** [comment]
It is in the running code but not updated on GitHub because I pulled against your repo.

**Comment by briis** [comment]
My fault, I forgot to commit the changes - It was Saturday morning and the wife wanted me to go shopping. Changes are now on the repo. Sorry, my fault.

**Comment by GlennGoddard** [comment]
I accept your apology for not fully fixing my mistakes right away.  You are forgiven.

Next time I makes mistakes (which will definitely happen) I expect prompt correction in all locations.

**Comment by briis** [comment]
Thank you, and I will make sure to fix it all next time 😁 Have a good Sunday when you get to that.

**Pull request closed without merging**
