### PR TITLE
Zambretti

### PR DESCRIPTION
**Pull request by GlennGoddard**
I only have a placeholder for the Danish Translation, I did this to make it easier for who ever will do the translation for Danish.  I added French, English, and German translations as they were readily available.  The placeholder is a copy of the English.

I simplified the code for Zambretti Text to just have the letter A-Z and send the letter to the translation call; I think this makes it easier to follow.

I don't know how to pull in the All Time Sea Level Pressure Max or Min (p_hi, p_lo are variables I used as placeholder).  If this can not be done to pull this easily from SQL then it could be a Environmental variable put in by user.

I removed references to wind_speed in zambretti since it I removed it from the formula earlier.

### CODE REVIEW

**Comment by briis** [comment]
Hi Glenn,
I now did the initial Merge but I have a few questions to understand the parameters for the function.
You pass the following:
- Latitude: This is OK, we have that data.
- Wind Direction Avg: OK, we have that data.
- All Time Sea Level Pressure High and Low: As you write you don't know how to do that. But what value are you looking for? The All Time recorded values for the station or for the current location? If it is the first, then we can read it from the database, but it will not be very accurate before the Integration has ran for a long time. 
If it is the second, then we could simply supply it as a parameter, with default values of 960 for low and 1050 for high. (Which I think will be more accurate than the first option).
- Sea Level Pressure: I assume this is the current Sea Level pressure and we have that data

**Comment by briis** [comment]
I have now uploaded a new `dev` build to docker, which contains the Zambretti Forecast. High and Low Pressure values are currently 1060 and 960 hardcoded in to the formula, but easy to change if needed.
I had to do some modifications to the formula, as you used String Values for Wind Direction and Pressure Trend, and that does not work if you do not run the English language. So this is now changed to Pressure Trend Value and Average Wind Bearing.

Please test this out, and give me some feedback on the High/Low values and what you expect to see here.

**Comment by GlennGoddard** [comment]
For all time sea level pressure, I did mean for the station but also suggested an environment variable to allow user selection for the hi and low since they do change globally.

I did not think about the translation issue with cardinal wind direction.

I will have to compare code but what I have running locally on my test is 1 and this is returning 25.

**Comment by briis** [comment]
Ok, then I think we are aligned, and we could use two Environment Variables for the High and Low values. Whar values do you currently use for your local system that returns 1?
This system uses 1060 for High and 960 for Low

**Comment by GlennGoddard** [comment]
I'll have to convert but all time hi: 30.669
Low: 29.25

**Comment by GlennGoddard** [comment]
I pull from the station all time Min and Max and convert back to mmHg from Inches in the formula

**Comment by GlennGoddard** [comment]
My current is:
991 min
1039 max

**Comment by briis** [comment]
These values make a huge difference, so that may explain the variation. Why did you pick these values? I mean where did you get them from?

I will work on a new dev build that makes it possible to set these values from the Docker Environment

**Comment by GlennGoddard** [comment]
I think in the previous PR that I gave more info (the one I closed to add the translations).

I assume it will not be easy to pull the SQL data back in to the integration for these calculations?

**Comment by briis** [comment]
I would rather not go down that route, as it has proven to be too unstable with the SQL Data.
If it is all-time high low, then the best source is also not the local weather station, as this might not have been running for long enough to get decent values.

**Comment by GlennGoddard** [comment]
I had the same thoughts.  I will see if I can find a good weather site that gives world wide Min and Max for any specific location or maybe ones for regions.

I changed the hard coded min and max but I'm still getting the 25 vice my now 4.  I forced the change in helpers.py for my testing right now.  For some reason the Zambretti Number is stuck on 25 output when it should not be.

**Comment by GlennGoddard** [comment]
Ok, something is wrong with the calling function.  I set z_number = 0 right before the return but my output in HA is still 25 (yes, I restarted the container)

**Comment by GlennGoddard** [comment]
I think the issue is the z_hi and z_lo I used in sensor_description and I don't know if zambretti_number (sensor_description.py) and zambretti_value (weatherflow_mqtt.py) being different has an effect.

I am removing for test now. 
You are probably sleeping right now, so I'll test and post what I find out.

**Comment by GlennGoddard** [comment]
[https://www.wunderground.com/history](https://www.wunderground.com/history)
Not perfect but gives you the high and low for any month/year and then you can select different months to find the min/max for your area.

**Comment by briis** [comment]
I am almost done adding the Variables for High and Low, and will make a new dev build tomorrow morning (my time)
A few questions:
- Did you come any closer to discover the bug around z_hi and Z-lo?
- Would you prefer that if user sets imperial as units (Like you do), that you then enter the High and Low Pressure value in `inHg` or should we keep it in `Mb` for all users?

**Comment by GlennGoddard** [comment]
I didn't figure out my issue, something around Docker changed lately and it appears changes inside containers don't take effect.

MB is common enough and easy to convert to.

**Comment by briis** [comment]
Thanks. A new dev is out tomorrow, where you can change High/Low and do some real testing.

**Comment by briis** [comment]
The new `dev` build is ready. Here is the preliminary text I wrote in the Changelog, and there you can see the name of the Docker Environment Variables for High and Low Pressure. Let me know how that goes.

- Added new sensors `zambretti_number` and `zambretti_text`, which are sensors that uses local data to create Weather Forecast for the near future. In order to optimize the forecast, these values need the *All Time High and Low Sea Level Presurre*. Per default these are set to 960Mb for Low and 1060Mb for High. They can be changed by adding the Environment Variables `ZAMBRETTI_MIN_PRESSURE` and `ZAMBRETTI_MAX_PRESSURE` to the Docker Start command.

**Comment by GlennGoddard** [comment]
Updated and still getting 25, should be 10 as I calculate.  Probably a imperial/metric issue somewhere.

**Comment by GlennGoddard** [comment]
Got it, I changed my input from MB to inHG in the environmental variable and everything matches now.   So it was an imperial/metric issue...just on my part.

**Comment by briis** [comment]
I was just about to write that. I will need to make sure that I use inHG as default values when no values are supplied, and we need to ensure that the documentation states what unit to use for High and Low. I am on my way out, but see if I can just quickly adjust for the default values and then do a new build.

**Comment by GlennGoddard** [comment]
Wait 10 sec, I am writing that in Readme right now already

**Comment by briis** [comment]
Pushed a new `dev` build with conversion of default values to inHG if unit system = imperial.
Try and remove your environment vars from the Docker run and just see if this now returns something different than 25.

**Comment by GlennGoddard** [comment]
still 25 with no input, but fine with my actual values.

**Comment by GlennGoddard** [comment]
Actually...the new build didn't get pulled yet from Docker Hub....Not available yet

**Comment by GlennGoddard** [comment]
Updated ReadMe with new PR.

I will start work on a new PR for current conditions, fog and snow probability.  My wife is dragging me to a birthday party today, so I don't know how far I will get.

**Comment by briis** [comment]
Thanks. I'll clean-up the code I just did and make sure it works.

**Comment by GlennGoddard** [comment]
One thing that could be improved is the pressure trend.  I don't know how to implement that change thou.  I 'true' rise is 1.6 inHG (5.4 MB) rise in 3 hours, falling is 1.6 inHG drop in 3 hours, and steady is if there is no rise or fall of 1.6 inHG in the last 3 hours.

Is there a way we can have a global variable that has the highest pressure in the last 3 hours?  Same with lower.  Probably an array that has the time stamp of those highs and lows.

**Comment by briis** [comment]
The pressure is already stored for 3 hours ago in the SQL DB, as this is what is used to calculate the Pressure Trend text and value. The Zambretti Number formula is also changed to look at the Pressure Trend value instead of the Text, but currently I just look if it is greater than, smaller than or equal to 0.

Just to make sure, the value I pull is the Actual pressure 3 hours ago, and then I compare that to the current pressure to get the trend. For Zambretti it would be easy enough to compare against >1.6inHG or <1.6inHG, but is that what you are asking for?

**Comment by GlennGoddard** [comment]
Kinda, that would be better.  The algorithm is looking for any accumulated change of 1.6 inHg at any point during 3 hours even if not 1.6 total.

My explanation just made it more confusing.   So, what you suggest would work better in this case.

**Comment by briis** [comment]
I just pushed a new dev build. In the Zambretti Number formula this will now use the *rising* formula if the Pressure Trend is above 1.6inHG and the *falling* formula if the trend is below 1.6inHG and the rest is *Steady*. It looks like this:

```python
        z_trend_threshold = 1.6 if self.unit_system == UNITS_IMPERIAL else 5.4
        if float(trend) < z_trend_threshold:
            z_trend = 2
        elif float(trend) > z_trend_threshold:
            z_trend = 1
        else:
            z_trend = 0
````
Test it out and see how this works.

**Comment by GlennGoddard** [comment]
It appears to always assume falling trend.  Right now I have a rising trend but getting a result as if falling.  It was tracking fine earlier today when pressure was indeed falling.

**Comment by briis** [comment]
I think 1.6inHG is too high a number. If I look at my station the drop in the last 24 hours is only 4.1Mb, and based on that it will never go to rising. It will only be in extreme cases that you will see such a big drop (or rise) within a 3 hour period.

Where did you get that number from?

**Comment by GlennGoddard** [comment]
Well....the 1.6 is right....the units are not.  I just verified and it is 1.6 Mb change.  I remembered the 1.6 (of course did not go back and verify at the tiem), but I got the units wrong and then I just converted from inHG to Mb.

[https://communities.sas.com/t5/Streaming-Analytics/Zambretti-Algorithm-for-Weather-Forecasting/td-p/679487](https://communities.sas.com/t5/Streaming-Analytics/Zambretti-Algorithm-for-Weather-Forecasting/td-p/679487)

**Comment by briis** [comment]
Ok, so the value should be 0.047248 inHG instead of 1.6. And then the 1.6 is Mb - that makes more sense.
If we agree then I will correct when I get bak from work in 2-3 hours, and build again.

**Comment by GlennGoddard** [comment]
I agree with the conversion.

**Comment by briis** [comment]
Great. I will post here when a new build is uploaded.

**Comment by briis** [comment]
Done. New `dev` build uploaded. The threshold now looks like this:

```python
z_trend_threshold = 0.047248 if self.unit_system == UNITS_IMPERIAL else 1.6
````

**Comment by GlennGoddard** [comment]
Better but still doesn't match my other code running; however, they are both accurate.
I will let it run for a few days, especially since I have changing weather this week, that way you should be able to push this out on your weekend to stable.

I have found that the Zambretti at least so far this week is more accurate then any weather app forecast (other than WeatherFlow's).  Zambretti was predicting rain yesterday, no other weather app went above 10% chance of rain (which I guess is still a chance)....today it was raining.  Of course, after it started raining 'some' of the apps raised the chance of rain to 60%.

Perhaps in the future I can either 'getting a feeling' for the % chance of rain based on Zambretti output or I can find what others have determined.

I realize the Zambretti is a relatively simplistic forecast tool, but I'm impressed so far.

**Comment by GlennGoddard** [comment]
I have rising/steady trend for last 6 hours and a 14 Zambretti #.  14 is only available for a falling trend.  I think it is something to do with the trend function.

Maybe set the output of the Zambretti number function to that of trend value (I forget the variable you used and I'm on my phone) temporarily for testing.

**Comment by briis** [comment]
I then think the best option is just to check if the Trend is Rising, Falling or Steady as your original formula was doing. I will change this now, and push a new dev build before I head of to work.

**Comment by GlennGoddard** [comment]
I pulled the PR before I went to work and it seems to be tracking but I have stable weather now.  It was one number lower than my separate calculations for a few hours, but that could be a variety of reasons.  At current it seems acceptable, I will let you know if there are any other issues.

I am curious why the trend value you tried didn't work.

**Comment by briis** [comment]
Good to hear. Just timing of the readings of values can lead to the small difference in the Zembretti number returned, and that can be the explanation of the small variance.

> I am curious why the trend value you tried didn't work.

Basically I think the issue is that in most circumstances the variation in trend over a 3 hour period, is not that big and thus it will not be accurate enough with the values supplied. An adjustment in the value might help, but I would not know what the right value would be and it might even vary based on the location your weather station is located.

**Comment by GlennGoddard** [comment]
Looks good, I think this is the best we can get for now.
My recommendation is to pull in the PR for the readme and then release to Stable.

Once Stable is updated, I will work on the current conditions PR.  I might get it to you by before next weekend.  4th of July (American Independence Day) is coming up and we like our fireworks and BBQ, so I probably won't get much done on it this weekend.

**Comment by briis** [comment]
Thanks. I will release later today, just need some final stability tests after I upgraded the core to Python 3.10 (as HA is also moving to in 2022.7).

**Comment by briis** [comment]
Everything is running at my end - just give this latest `dev` build a try and let me know if it is also error free for you, then I will push it to stable.

**Comment by GlennGoddard** [comment]
Seems to be running just fine for me.  No errors noticed.

**Comment by GlennGoddard** [comment]
When you push to stable the 3 sensors listed as in Dev build in the Sensors Under Development section can be removed.  No rush on updated that however.

**Comment by GlennGoddard** [comment]
I created a new PR that removed those from sensors from the 'Under Development' area.  I also fixed a spelling error.

**Pull request merged**
